apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-hooks
spec:
  selector:
    matchLabels:
      app: auth-hooks
  template:
    metadata:
      labels:
        app: auth-hooks
    spec:
      serviceAccountName: auth-hooks
      imagePullSecrets:
        - name: docker-registry
      containers:
        - name: auth-hooks
          image: communicator
          resources:
            requests:
              memory: '128Mi'
              cpu: '200m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: ENV
              value: dev

          livenessProbe:
            httpGet:
              path: /healthz
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 30

          readinessProbe:
            tcpSocket:
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 60
