apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-hooks
  annotations:
    konghq.com/protocols: https
    konghq.com/https-redirect-status-code: '308'
    konghq.com/plugins: cors,key-auth
    konghq.com/strip-path: 'true'
    konghq.com/preserve-host: 'false'
spec:
  tls:
    - hosts:
        - dev-api-communicator.lootlog.pl
      secretName: tls
  ingressClassName: kong
  rules:
    - host: dev-api-communicator.lootlog.pl
      http:
        paths:
          - path: /auth-hooks
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-hooks
                port:
                  number: 4000
